Initial tests
valorem-labs-inc/valorem-erc20-factory pull request #4
Opened 2022-12-01 15:14 UTC by Flip-Liquid

2022-12-01 15:15 UTC, Flip-Liquid commented
re-enable coverage and static analysis, add initial test for factory.

2022-12-02 18:59 UTC, 0xAlcibiades approved these changes

2022-12-02 19:00 UTC, 0xAlcibiades commented
Fix slither remappings, please

2022-12-02 19:58 UTC, 0xAlcibiades requested changes
@Flip-Liquid can you add the valorem-core as a submodule here and fix the slither remappings, it's still failing?

2022-12-02 20:07 UTC, 0xAlcibiades approved these changes

2022-12-02 20:07 UTC, merged